### ISSUE TITLE
Question about Data Set 

### ISSUE THREAD

**Issue by AbdulXIA** [tonyreina/chemistry#1]
Dear Tony, thank you for such a detailed example, I am very glad for this opportunity to use it.

I have a question about the reliability of the data. All data given in logP_dataset.csv is experimental? May I know the source of this data?
I can use the model to predict LogP
Thank you

**Comment by tonyreina** [comment]
https://www.kaggle.com/datasets/matthewmasters/chemical-structure-and-logp

Yes. It is from the Kaggle datasets. A reference can be found in the notebook.
